language: node_js
node_js: 10.15.1
jobs:
  include:
    - stage: lint
      name: lint
      script: yarn lint
    - stage: End 2 end testing
      script: yarn end2end
    - stage: deploy to production
      script: yarn build
      before_deploy: "echo 'listing build' && ls build"
      deploy:
        provider: firebase
        skip_cleanup: true
        token:
          secure: "$FIREBASE_ACCESS_TOKEN"
        message: "Firebase token"
        local_dir: build
        on:
          branch: master
