language: node_js
node_js:
  "10.15.1"

jobs:
  include:
    - stage: "lint"
      name: "lint"
      script: ./lint
    - stage: "build"
      script: "yarn build"
    - stage: deploy
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_ACCESS_TOKEN
        local_dir: build
        on:
          branch: master


