language: node_js
node_js: 10.15.1
jobs:
  include:
    - stage: lint
      name: lint
      script: "./lint"
    - stage: deploy to staging
      script: yarn build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: "$GITHUB_ACCESS_TOKEN"
        local_dir: build
        on:
          branch: master
    - stage: deploy to production
      scripg: yarn build
      deploy:
        provider: firebase
        skip_cleanup: true
        token:
          secure: "g8YFhucM1ps16ZoFbTlO55SDmme84UfaDvS+j0zoQtENOBzESZovZsN1lq5KwUOSRcx1IvEfVDLKb7GJ/B84FAq0gZucwWKYczfE7/vQDgKfzCnQ/hL32PoWOHR5+ON3JV302xkcHakpRprF+0sizPdIdMV8pOb23DR3+vrDeMM9laNqzBo3uPQzlUrqVu8jLMnQajs1LrC0stgtmKoEu3HmBxTYqZTi2GH81DOvMMa5b7MSML/cUa5+a/j0bgm7EgN2XCxP7V1XFO7rO6QVvhb2EzA4+7eMVKaLsiKKksclOYNghO2/k5TLL6v1Dt0XlVos0J3PRZnvURdrjBWWjEwNaD1uDznva4s7dhTxB8uejAFHBlNGvn5EGzt/yhvNEN6RT2DWXCtbv4XmKGsKY0n4cgdpJ9H2qv3C9lHjf3/U4/cogipC1BihUo0ueqKW00pe6mNyz05eWUqCzYtSJG9ZkdZtZmFkNDQH7gz1uH6ma5cpBuca6NNvVkmbEpHzTAPKjTq7+hz+9WmAmWhoI8/ZZZIC7jmk2ZZqY1xuDwI6undHEZWWf67GJBEipXMrkr3KsfRg4AnYLAVPqrqBDa9dY8wIZ5oimeFM9BUvX9J8ni6a1JCQVpqmS4jNd7P/8+oJNSo+LIlZ++Aimg4CIQVqqAIUMSJt8xHX/JvmcVs="
        local_dir: build
        on:
          branch: master
