language: node_js
node_js: 10.15.1
jobs:
  include:
    - stage: lint
      name: lint
      script: "./lint"
    - stage: deploy to staging
      script: yarn build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: "$GITHUB_ACCESS_TOKEN"
        local_dir: build
        on:
          branch: master
    - stage: deploy to production
      scripg: yarn build
      before_deploy: "echo 'ready?'"
      deploy:
        provider: firebase
        skip_cleanup: true
        token:
          secure: "$FIREBASE_ACCESS_TOKEN"
        message: "Firebase token"
        local_dir: build
        on:
          branch: master
