language: node_js
node_js: 10.15.1
jobs:
  include:
    - stage: lint
      name: lint
      script: "./lint"
    - stage: deploy to staging
      script: yarn build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: "$GITHUB_ACCESS_TOKEN"
        local_dir: build
        on:
          branch: master
    - stage: deploy to production
      scripg: yarn build
      deploy:
        provider: firebase
        skip_cleanup: true
        token:
          secure: zjs/EeOWHee/tgio0DyGu/tjnCIK6fw+C1mxEwxalggkS7wE3/kMulqq3WazaWVhp9BmVSo2sMPbxPDYBqFxPV43SF9BGfsRYu8TIb7hsKzzH4PH1J/qgPE2eqo/v1UsOT3IKKNYlXe8mePdT9Y/QWy9+Z/Yh6xYejEfGwGI1CRFw0On8CRpd82qRcSN9ClzlzdflzRL18uRRk08onwW0uywmMMHBAzkiZRGWID8ozWQ9PwIn0huOLBzEcqTZHr87NQWZlc8FXrrLFDcGFZu3fRp30ndyZ0GnMtU/N4gmrQHI1zQSJsMuBdyHcgfTg7px+kLC8GvyKHhpPWSYhbNqeCEZQ/K3jmsd6/qtx33Y346mUgZ0TK3I49rLcemsmK1/mk3Gt8K8TluoOl/LOhH6CI49opRXdyy5OGZNn3LxET4oN89IVphSD6VK8Or66PV8TVsuxLD/FfwrjOILZRHtYXvCnOMbdr1+ElXvxrTWPZqUe/zsymFpOIiMX1t7My6RPdfbaU5dB4IUD20fCjdkoezdaAGosW15Y6fEkiEMc/uyhx62dFEo01DfVp0wuEubbknsB/J6C3e+PFFWCDO2GOmqeJev6KMPqNWHcMWuC96i/i5ZXYP1wtlUpBppfNzGiYeJsbAAXPF5vdlAzNOtzpcZIWgPgN9hwPNQ4x+qQE=
        local_dir: build
        on:
          branch: master
env:
  global:
    secure: zjs/EeOWHee/tgio0DyGu/tjnCIK6fw+C1mxEwxalggkS7wE3/kMulqq3WazaWVhp9BmVSo2sMPbxPDYBqFxPV43SF9BGfsRYu8TIb7hsKzzH4PH1J/qgPE2eqo/v1UsOT3IKKNYlXe8mePdT9Y/QWy9+Z/Yh6xYejEfGwGI1CRFw0On8CRpd82qRcSN9ClzlzdflzRL18uRRk08onwW0uywmMMHBAzkiZRGWID8ozWQ9PwIn0huOLBzEcqTZHr87NQWZlc8FXrrLFDcGFZu3fRp30ndyZ0GnMtU/N4gmrQHI1zQSJsMuBdyHcgfTg7px+kLC8GvyKHhpPWSYhbNqeCEZQ/K3jmsd6/qtx33Y346mUgZ0TK3I49rLcemsmK1/mk3Gt8K8TluoOl/LOhH6CI49opRXdyy5OGZNn3LxET4oN89IVphSD6VK8Or66PV8TVsuxLD/FfwrjOILZRHtYXvCnOMbdr1+ElXvxrTWPZqUe/zsymFpOIiMX1t7My6RPdfbaU5dB4IUD20fCjdkoezdaAGosW15Y6fEkiEMc/uyhx62dFEo01DfVp0wuEubbknsB/J6C3e+PFFWCDO2GOmqeJev6KMPqNWHcMWuC96i/i5ZXYP1wtlUpBppfNzGiYeJsbAAXPF5vdlAzNOtzpcZIWgPgN9hwPNQ4x+qQE=
