# build environment
FROM node:10-slim as builder
RUN mkdir /app
WORKDIR /app
COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock
COPY tsconfig.json /app/tsconfig.json
COPY public /app/public
COPY src /app/src
RUN yarn
ENV PATH /app/node_modules/.bin:$PATH
RUN yarn build

# production environment
FROM nginx:1.13.9-alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
